include:
  - project: quantum/cicd/templates/python
    file: quantum-toolbox-template-microlib.yml
    ref: "v1.2.0"


python:twine:
  rules:
    - when: never

semantic-release:
  rules:
    - when: never

find-next-release:
  rules:
    - when: never
